### ISSUE TITLE
"settings.json"file inside has disappeared

### ISSUE THREAD

**Issue by ahaxxxx** [Hydraallen/Latex-vscode#1]
I downloaded the code, but the "settings.json"file inside has disappeared. 
Can you re-upload it? Thank you very much!

**Comment by Hydraallen** [comment]
It's actually inside the package with a different name. You need to rename the file or just use it for reference.
For windows: https://github.com/Hydraallen/Latex-vscode/blob/main/Windows/vscode-settings.json
For macOS: https://github.com/Hydraallen/Latex-vscode/blob/main/MacOS/vscode-settings.json

**Comment by ahaxxxx** [comment]
I understand now, thank you very much!
